# This payload should be generated by service that gets list of instruments to scrape
class PendingInstrument < Dry::Struct
  transform_keys(&:to_sym)

  attribute :url, Types::String
  attribute? :asset, Types::String.optional
  attribute? :name, Types::String.optional
  attribute? :symbol, Types::String.optional
  attribute? :isin, Types::String.optional
end